<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attribute {attribute} must be array.' => '',
    'Authclient Extension not support "{serviceName}" service' => '',
    'Component is not configured!' => '',
    'Component must be instance of SyncService class' => '',
    'Connect' => '',
    'Disconnect' => '',
    'ID post' => '',
    'ID service author' => '',
    'Run synchronization' => '',
    'Service could not be connected' => '',
    'Service is not connected' => '',
    'Service list has wrong value' => '',
    'Service name' => '',
    'Service was successfully connected' => '',
    'Service was successfully disconnected' => '',
    'Service was successfully synchronized! There\'s no new records!' => '',
    'Service was successfully synchronized! {count} record(s) was added!' => '',
    'Set model attribute to synchronization' => '',
    'Set model class to synchronization' => '',
    'Sign' => '',
    'Social network' => '',
    'Status' => '',
    'SyncSocial Component is not configured!' => '',
    'SyncSocial Extension not support "{serviceName}" service' => '',
    'SyncSocial is not support {serviceName}.' => '',
    'Synchronization with social networks' => '',
    'There is a error in service synchronization' => '',
    'There is error in disconnection' => '',
    'Time created' => '',
    'Wrong model configuration for SyncSocial extension' => '',
    'Wrong sync model configuration for SyncSocial extension' => '',
    '{service} not support post delete' => '',
    '{service} not support post publish' => ''
];
